export type PageName =
  | "home"
  | "login"
  | "signup"
  | "marketplace"
  | "ai-analysis"
  | "ai-analysis-result"
  | "register-material"
  | "trade-status"
  | "material-detail"
  | "material-rental-detail"
  | "my-page-profile"
  | "my-page-badges"
  | "my-page-registered-materials"
  | "my-page-activity"
  | "my-page-esg-report";
